config/routes.rb
Key0101::Application.routes.draw do
  resources :keys

  resources :for_selects

end

app/models/for_select.rb
class ForSelect < ActiveRecord::Base

	# Create a 2d array to be used in "grouped_options_for_select" in "select-tag"
	# "db_model" is the name of the model containing all the select information
	# "code" is the value in the code field in the db_model that identifies
		# which group of values will appear in the grouped select
	# "grouped_options" is my gem which generates the 2d array
		# gem 'grouped_options', git: 'git@github.com:marcmentis/grouped_options.git'
	def self.GroupedSelect(facility, code, db_model)
		@forSelect = db_model.all
					  .where(facility: facility)
                      .where(code: code)
                      .order(option_order: :asc)  
	    # @grouped_options = ForSelect.grouped_options(@forSelect)
	    @grouped_options = GroupedOptions.grouped_options(@forSelect)
		
	end

	def self.CollectionForSelect(facility, code, db_model)
		select_collection = db_model.where(facility: facility)
									.where(code: code)
									.order(option_order: :asc)
	end
end

app/models/key.rb
class Key < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/for_selects_controller.rb
class ForSelectsController < ApplicationController
  before_action :set_for_select, only: [:show, :edit, :update, :destroy]

  # GET /for_selects
  # GET /for_selects.json
  def index
    @for_selects = ForSelect.all
  end

  # GET /for_selects/1
  # GET /for_selects/1.json
  def show
  end

  # GET /for_selects/new
  def new
    @for_select = ForSelect.new
    # Generate the 2d array needed for grouped select in view
#    @grouped_options = ForSelect.GroupedSelect('9999','facility', ForSelect)
  end

  # GET /for_selects/1/edit
  def edit
    # Generate the 2d array needed for grouped select in view
    @grouped_options = ForSelect.GroupedSelect('9999','facility', ForSelect)
  end

  # POST /for_selects
  # POST /for_selects.json
  def create
    @for_select = ForSelect.new(for_select_params)

    respond_to do |format|
      if @for_select.save
        format.html { redirect_to @for_select, notice: 'For select was successfully created.' }
        format.json { render action: 'show', status: :created, location: @for_select }
      else
        format.html { render action: 'new' }
        format.json { render json: @for_select.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /for_selects/1
  # PATCH/PUT /for_selects/1.json
  def update
    respond_to do |format|
      if @for_select.update(for_select_params)
        format.html { redirect_to @for_select, notice: 'For select was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @for_select.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /for_selects/1
  # DELETE /for_selects/1.json
  def destroy
    @for_select.destroy
    respond_to do |format|
      format.html { redirect_to for_selects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_for_select
      @for_select = ForSelect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def for_select_params
      params.require(:for_select).permit(:code, :value, :text, :grouper, :option_order, :facility, :created_at, :updated_at)
    end
end

app/controllers/keys_controller.rb
class KeysController < ApplicationController
  before_action :set_key, only: [:show, :edit, :update, :destroy]

  # GET /keys
  # GET /keys.json
  def index
    @search = Key.search(params[:q])
    @keys = @search.result.page(params[:page]).per(10)
#    @keys = Key.all
  end

  # GET /keys/1
  # GET /keys/1.json
  def show
  end

  # GET /keys/new
  def new
    @key = Key.new
  end

  # GET /keys/1/edit
  def edit
  end

  # POST /keys
  # POST /keys.json
  def create
    @key = Key.new(key_params)

    respond_to do |format|
      if @key.save
        format.html { redirect_to @key, notice: 'Key was successfully created.' }
        format.json { render action: 'show', status: :created, location: @key }
      else
        format.html { render action: 'new' }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keys/1
  # PATCH/PUT /keys/1.json
  def update
    respond_to do |format|
      if @key.update(key_params)
        format.html { redirect_to @key, notice: 'Key was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keys/1
  # DELETE /keys/1.json
  def destroy
    @key.destroy
    respond_to do |format|
      format.html { redirect_to keys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_key
      @key = Key.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def key_params
      params.require(:key).permit(:Company, :Description, :Number, :Checkout, :Checkin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/for_selects_helper.rb
module ForSelectsHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/views/for_selects/_form.html.erb
<%= form_for(@for_select) do |f| %>
  <% if @for_select.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@for_select.errors.count, "error") %> prohibited this for_select from being saved:</h2>

      <ul>
      <% @for_select.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :grouper %><br>
    <%= f.text_field :grouper %>
  </div>
  <div class="field">
    <%= f.label :option_order %><br>
    <%= f.number_field :option_order %>
  </div>
  <div class="field">
    <%= f.label :facility %><br>
    <%= f.text_field :facility %>
 <%#= f.select(:facility, grouped_options_for_select(@grouped_options), prompt: 'Choose Facility') %>
        <%= select_tag(:sFor_select_facility, grouped_options_for_select(@grouped_options), prompt: 'Choose Facility') %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br>
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/for_selects/edit.html.erb
<h1>Editing for_select</h1>

<%= render 'form' %>

<%= link_to 'Show', @for_select %> |
<%= link_to 'Back', for_selects_path %>

app/views/for_selects/index.html.erb
<h1>Listing for_selects</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Value</th>
      <th>Text</th>
      <th>Grouper</th>
      <th>Option order</th>
      <th>Facility</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @for_selects.each do |for_select| %>
      <tr>
        <td><%= for_select.code %></td>
        <td><%= for_select.value %></td>
        <td><%= for_select.text %></td>
        <td><%= for_select.grouper %></td>
        <td><%= for_select.option_order %></td>
        <td><%= for_select.facility %></td>
        <td><%= for_select.created_at %></td>
        <td><%= for_select.updated_at %></td>
        <td><%= link_to 'Show', for_select %></td>
        <td><%= link_to 'Edit', edit_for_select_path(for_select) %></td>
        <td><%= link_to 'Destroy', for_select, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New For select', new_for_select_path %>

app/views/for_selects/new.html.erb
<h1>New for_select</h1>

<%= render 'form' %>

<%= link_to 'Back', for_selects_path %>

app/views/for_selects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @for_select.code %>
</p>

<p>
  <strong>Value:</strong>
  <%= @for_select.value %>
</p>

<p>
  <strong>Text:</strong>
  <%= @for_select.text %>
</p>

<p>
  <strong>Grouper:</strong>
  <%= @for_select.grouper %>
</p>

<p>
  <strong>Option order:</strong>
  <%= @for_select.option_order %>
</p>

<p>
  <strong>Facility:</strong>
  <%= @for_select.facility %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @for_select.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @for_select.updated_at %>
</p>

<%= link_to 'Edit', edit_for_select_path(@for_select) %> |
<%= link_to 'Back', for_selects_path %>

app/views/keys/_form.html.erb
<%= form_for(@key) do |f| %>
  <% if @key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@key.errors.count, "error") %> prohibited this key from being saved:</h2>

      <ul>
      <% @key.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Company %><br>
    <%= f.text_field :Company %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description %>
  </div>
  <div class="field">
    <%= f.label :Number %><br>
    <%= f.number_field :Number %>
  </div>
  <div class="field">
    <%= f.label :Checkout %><br>
    <%= f.date_select :Checkout %>
  </div>
  <div class="field">
    <%= f.label :Checkin %><br>
    <%= f.date_select :Checkin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keys/edit.html.erb
<h1>Editing key</h1>

<%= render 'form' %>

<%= link_to 'Show', @key %> |
<%= link_to 'Back', keys_path %>

app/views/keys/index.html.erb
<h1>Listing keys</h1>

<%= paginate @keys %>

<%= search_form_for @search do |f| %>
  <div class="field">
    <%= f.label :Company_cont, "Name contains" %>
    <%= f.text_field :Company_cont %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link @search, :Company, "Company" %></th>
      <th>Description</th>
      <th><%= sort_link @search, :Number, "Number" %></th>
      <th><%= sort_link @search, :Checkout, "Checkout" %></th>
      <th><%= sort_link @search, :Checkin, "Checkin" %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @keys.each do |key| %>
      <tr>
        <td><%= key.Company %></td>
        <td><%= key.Description %></td>
        <td><%= key.Number %></td>
        <td><%= key.Checkout %></td>
        <td><%= key.Checkin %></td>
        <td><%= link_to 'Show', key %></td>
        <td><%= link_to 'Edit', edit_key_path(key) %></td>
        <td><%= link_to 'Destroy', key, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Key', new_key_path %>

app/views/keys/new.html.erb
<h1>New key</h1>

<%= render 'form' %>

<%= link_to 'Back', keys_path %>

app/views/keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @key.Company %>
</p>

<p>
  <strong>Description:</strong>
  <%= @key.Description %>
</p>

<p>
  <strong>Number:</strong>
  <%= @key.Number %>
</p>

<p>
  <strong>Checkout:</strong>
  <%= @key.Checkout %>
</p>

<p>
  <strong>Checkin:</strong>
  <%= @key.Checkin %>
</p>

<%= link_to 'Edit', edit_key_path(@key) %> |
<%= link_to 'Back', keys_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Rockland PC", "http://rpcweb.omh.ny.gov" %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "For Select", for_selects_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Key", keys_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Contact Us" %></li>
      <li class="divider"></li>
      <li><%= link_to "Cart" %></li>
    </ul>
  </section>
</nav>

<div class="row">
  <div class="large-8 columns"><h2>More information</h2></div>
  <div class="large-4 columns">
    <h2 class="subheader">About Us</h2>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </div>
</div>

<%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>